* Overview

*NOTE*: This is still early stage development

`wakame-mode` is a non-official wakatime mode for Emacs. It's a
re-implementation of [[https://github.com/wakatime/wakatime-mode][wakatime-mode]] without relying on [[https://github.com/wakatime/wakatime-cli][wakatime-cli]] and instead
makes API calls directly. It is only tested with [[https://github.com/muety/wakapi][wakapi]] and might or might not
work with [[https://wakatime.com][wakatime.com]].

Main reason for this re-implementation is lack of some features when working
with official wakatime-mode and wakatime-cli. Specifically with native
implementation we get:

- Support for remote files with Tramp (see [[https://github.com/wakatime/wakatime-mode/issues/27][wakatime-mode issue #27]])
- Support for project.el and projectile to detect projects
- Support for reporting non-file buffers (org-agenda, dired, proced and others)
  as "app" type


* Known Issues

- Language detection works differently. For example instead of "Emacs Lisp" we
  report "Elisp". This works with wakapi, but might be rejected by wakatime.com
  (untested)?
- We spoof user agent because wakapi ignores editor/OS in heartbeats and instead
  parses user agent to detect these.
- Hard dependencies on magit and maybe others

* TODOs

- Support for hook, overrides, ignores etc to tweak behaviour easily
- Document API key setup (and usage)
- Prevent autosaves from triggering save events (see wakapi-mode)
